env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

configmap:
  management:
    endpoints:
      web:
        exposure:
          include: info, health, prometheus, env, metrics, loggers
      prometheus:
        enabled: true
    metrics:
      endpoint:
        export:
          prometheus:
            enabled: true
  incoming:
    port: 8888
  polling:
    url:
      et: http4://anshar.default/anshar/rest/et
      vm: http4://anshar.default/anshar/rest/vm
      sx: http4://anshar.default/anshar/rest/sx
    period: 15s
  datasource:
    whitelist:
      et: RUT
      vm: RUT
      sx: RUT
  close_to_stop:
    percentage:
      vm: 95
    distance:
      vm: 500
  mqtt:
    enabled: false
    host: tcp://vernemq.default:1883
    username: kishar
    password: <password>
  pubsub:
    enabled: true
    topic:
      et: entur-google-pubsub://protobuf.estimated_timetables
      vm: entur-google-pubsub://protobuf.vehicle_monitoring
      sx: entur-google-pubsub://protobuf.situation_exchange
    credentials:
      path: file:///etc/kishar/credentials.json
  redis:
    enabled: true
    port: 6379

resources:
  cpuLimit: "7"
  memLimit: 6000Mi
  cpuRequest: "1"
  memRequest: 4500Mi
  xmx: 4g
  xss: 1024m

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

configMapMounts:
  - name: application-config
    mountPath: /etc/application-config
    subPath: ""
    configMap: kishar-config
    readOnly: false

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8888

secretMounts:
  - name: sa-key
    secretName: ror-kishar-sa-key
    mountPath: /etc/kishar/credentials.json
    subPath: credentials.json
    readOnly: true