env: staging

configmap:
  datasource:
    whitelist:
      et: RUT
      vm: RUT
      sx: RUT
  pubsub:
    project_id: radon-1287
  redis:
    enabled: false

ingress:
  enabled: true
  stagingIp: 35.233.47.68