env: staging

configmap:
  datasource:
    whitelist:
      et:
      vm:
      sx:
  pubsub:
    project_id: neon-1287
  redis:
    enabled: false

ingress:
  enabled: true
  stagingIp: 35.195.146.93