env: staging

configmap:
  datasource:
    whitelist:
      et:
      vm:
      sx:
  pubsub:
    project_id: neon-1287
  reddis:
    enabled: false
    url: 10.128.185.163:6379

ingress:
  enabled: true
  stagingIp: 35.195.146.93