apiVersion: v1
data:
  application.properties: |-
    kishar.incoming.port={{ .Values.configmap.incoming.port }}

    # URL to be used in Camel to fetch data
    kishar.anshar.polling.url.et={{ .Values.configmap.polling.url.et }}
    kishar.anshar.polling.url.vm={{ .Values.configmap.polling.url.vm }}
    kishar.anshar.polling.url.sx={{ .Values.configmap.polling.url.sx }}

    kishar.anshar.polling.period={{ .Values.configmap.polling.period }}

    kishar.datasource.et.whitelist={{ .Values.configmap.datasource.whitelist.et }}

    kishar.datasource.vm.whitelist={{ .Values.configmap.datasource.whitelist.vm }}

    kishar.datasource.sx.whitelist={{ .Values.configmap.datasource.whitelist.sx }}
kind: ConfigMap
metadata:
  name: {{ template "kishar.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
