apiVersion: v1
data:
  application.properties: |-
    management.endpoints.web.exposure.include={{ .Values.configmap.management.endpoints.web.exposure.include }}
    management.endpoints.prometheus.enabled={{ .Values.configmap.management.endpoints.prometheus.enabled }}
    management.metrics.endpoint.export.prometheus.enabled={{ .Values.configmap.management.metrics.endpoint.export.prometheus.enabled }}
    kishar.incoming.port={{ .Values.configmap.incoming.port }}
    kishar.anshar.polling.url.et={{ .Values.configmap.polling.url.et }}
    kishar.anshar.polling.url.vm={{ .Values.configmap.polling.url.vm }}
    kishar.anshar.polling.url.sx={{ .Values.configmap.polling.url.sx }}
    kishar.anshar.polling.period={{ .Values.configmap.polling.period }}
    kishar.datasource.et.whitelist={{ .Values.configmap.datasource.whitelist.et }}
    kishar.datasource.vm.whitelist={{ .Values.configmap.datasource.whitelist.vm }}
    kishar.datasource.sx.whitelist={{ .Values.configmap.datasource.whitelist.sx }}
    kishar.settings.vm.close.to.stop.percentage={{ .Values.configmap.close_to_stop.percentage.vm }}
    kishar.settings.vm.close.to.stop.distance={{ .Values.configmap.close_to_stop.distance.vm }}
    kishar.mqtt.enabled={{ .Values.configmap.mqtt.enabled }}
    kishar.mqtt.host={{ .Values.configmap.mqtt.host }}
    kishar.mqtt.username={{ .Values.configmap.mqtt.username }}

    kishar.pubsub.enabled={{ .Values.configmap.pubsub.enabled }}
    kishar.pubsub.topic.et={{ .Values.configmap.pubsub.topic.et }}
    kishar.pubsub.topic.tripupdate={{ .Values.configmap.pubsub.topic.tripupdate }}
    kishar.pubsub.topic.vm={{ .Values.configmap.pubsub.topic.vm }}
    kishar.pubsub.topic.vehicleposition={{ .Values.configmap.pubsub.topic.vehicleposition }}
    kishar.pubsub.topic.sx={{ .Values.configmap.pubsub.topic.sx }}
    kishar.pubsub.topic.alert={{ .Values.configmap.pubsub.topic.alert }}

    kishar.reddis.enabled={{ .Values.configmap.reddis.enabled }}
    spring.cloud.gcp.pubsub.project-id={{ .Values.configmap.pubsub.project-id }}
kind: ConfigMap
metadata:
  name: {{ template "kishar.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
