version: 2
aliases:
  - &GCP-auth
    name: GCP Authenticate
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/gcp_authenticate.sh
  - &docker-login
    name: Docker login
    command: |
      docker login -u _json_key --password-stdin https://eu.gcr.io <<< "${DOCKER_PASSWORD}"
  - &post-hook
    name: Notify about build and docker image pushed
    command: |
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
      /tools/build_notify.sh
  - &docker-build-and-push
    name: Docker build and push
    command: |
      IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
      echo "Image: ${IMAGE}"
      docker build -t $IMAGE .
      docker tag $IMAGE "$IMAGE":"${CIRCLE_BRANCH#"env/"}-v$CIRCLE_BUILD_NUM"
      docker tag $IMAGE "$IMAGE":"latest"
      docker push $IMAGE
  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      /tools/trigger_build_v2.sh "entur/kishar-deployment-config.git" "master" "$(git log -1 --pretty=%B)"
jobs:
  build:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn install -s /tools/m2/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
    - persist_to_workspace:
        root: ~/project
        paths:
        - target
        - Dockerfile
        - .circleci
  deploy-docker:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
    - attach_workspace:
        at: ~/project
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - setup_remote_docker:
        docker_layer_caching: true
    - add_ssh_keys:
        fingerprints:
          - $SSH_FINGERPRINT
    - run: *GCP-auth
    - run: *docker-login
    - run: *docker-build-and-push
    - run: *post_build
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: dev
    - deploy-docker:
        context: dev
        requires:
        - build
        filters:
          branches:
            only: master