version: 2.1
executors:
  cci-toolbox-java11:
    docker:
      - image: cimg/openjdk:21.0
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      MAVEN_OPTS: -Xmx3G
aliases:

  - &jfrog-settings
    name: Write artifactory settings to file
    command: |
      echo "$ARTIFACTORY_SETTINGS" | base64 --decode > .circleci/settings.xml

  - &save-test-results
    name: Save test results
    command: |
      mkdir -p ~/reports/junit
      find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/reports/junit/ \;
      find . -type f -regex ".*/target/owasp-reports/.*" -exec cp {} ~/reports/owasp/ \;

    when: always

  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      chmod +x .circleci/trigger_build_v2.sh
      .circleci/trigger_build_v2.sh "entur/kishar-deployment-config.git" "master" "$(git log -1 --pretty=%B)"

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    environment:
      MAVEN_OPTS: -Xmx5G
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: *jfrog-settings
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn install deploy -s .circleci/settings.xml
      - run: *save-test-results
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
      - run: *post_build

workflows:
  version: 2
  release:
    jobs:
      - build:
          name: build-release
          context: global
          filters:
            branches:
              only:
                - master